version: "3.7"

services:
  postgresdb:
    image: postgres:15.4
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  quasar:
    depends_on:
      postgresdb:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 50051:50051
    env_file:
      - app.env
