name: alyamamah
description: An app for alyamamah university students.
publish_to: "none"
version: 0.0.5+24

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_riverpod: 2.3.7
  auto_route: 7.8.0
  intl: any
  dio: 5.3.2
  dio_cookie_manager: 2.1.3 # check this
  cookie_jar: 3.0.1 # check this
  logging: 1.2.0
  shared_preferences: 2.2.0
  home_widget: 0.3.0
  url_launcher: 6.1.12
  hijri: 3.0.0
  flutter_svg: 2.0.7
  collection: any
  firebase_core: 2.15.1
  firebase_analytics: 10.4.5
  firebase_messaging: 14.6.6
  sentry_flutter: 7.9.0
  sentry_logging: 7.9.0
  sentry_dio: 7.9.0
  purchases_flutter: 5.6.2
  flutter_animate: 4.2.0+1
  unleash_proxy_client_flutter: 1.4.0
  permission_handler: 10.4.3
  flutter_inappwebview: 5.7.2+3
  crypto: 3.0.3
  package_info_plus: 4.1.0

dependency_overrides:
  intl: 0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: 1.0.0
  golden_toolkit: 0.15.0

  flutter_lints: 2.0.2

  build_runner: 2.3.3
  auto_route_generator: 7.3.1

  flutter_launcher_icons: 0.13.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/

  fonts:
    - family: IBM Plex Sans Arabic
      fonts:
        - asset: assets/fonts/IBM_Plex_Sans_Arabic/IBMPlexSansArabic-Thin.ttf
          weight: 100
        - asset: assets/fonts/IBM_Plex_Sans_Arabic/IBMPlexSansArabic-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/IBM_Plex_Sans_Arabic/IBMPlexSansArabic-Light.ttf
          weight: 300
        - asset: assets/fonts/IBM_Plex_Sans_Arabic/IBMPlexSansArabic-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBM_Plex_Sans_Arabic/IBMPlexSansArabic-Medium.ttf
          weight: 500
        - asset: assets/fonts/IBM_Plex_Sans_Arabic/IBMPlexSansArabic-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/IBM_Plex_Sans_Arabic/IBMPlexSansArabic-Bold.ttf
          weight: 700
