name: alyamamah
description: An app for alyamamah university students.
publish_to: "none"
version: 0.0.4+19

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_riverpod: 2.3.6
  auto_route: 7.4.0
  intl: any
  dio: 5.2.1+1
  dio_cookie_manager: 2.1.3 # check this
  cookie_jar: 3.0.1 # check this
  logging: 1.1.1
  shared_preferences: 2.1.2
  font_awesome_flutter: 10.4.0
  flutter_widgetkit: 1.0.3
  url_launcher: 6.1.11
  hijri: 3.0.0
  flutter_svg: 2.0.7
  collection: any
  firebase_core: 2.14.0
  firebase_analytics: 10.4.3
  firebase_messaging: 14.6.3
  sentry_flutter: 7.7.0
  sentry_logging: 7.7.0
  sentry_dio: 7.7.0
  purchases_flutter: 5.0.0
  flutter_animate: 4.1.1+1
  unleash_proxy_client_flutter: 1.2.1
  permission_handler: 10.3.0
  flutter_inappwebview: 5.7.2+3
  
dependency_overrides:
  intl: 0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: 0.3.0
  golden_toolkit: 0.15.0

  flutter_lints: 2.0.1

  build_runner: 2.3.3
  auto_route_generator: 7.1.1

  flutter_launcher_icons: 0.13.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/tajawal/Tajawal-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/tajawal/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/tajawal/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/tajawal/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/tajawal/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/tajawal/Tajawal-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/tajawal/Tajawal-Black.ttf
          weight: 900
