name: alyamamah
description: an app for alyamamah university.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_riverpod: 2.0.0-dev.9
  http: 0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/