name: alyamamah
description: An app for alyamamah university students.
publish_to: "none"
version: 0.0.1+8

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_riverpod: 2.3.6
  auto_route: 6.4.0
  intl: any
  dio: 5.1.1
  dio_cookie_manager: 3.0.0
  cookie_jar: 4.0.1
  logging: 1.1.1
  shared_preferences: 2.1.0
  font_awesome_flutter: 10.4.0
  flutter_widgetkit: 1.0.3
  url_launcher: 6.1.10
  hijri: 3.0.0
  flutter_svg: 2.0.5
  collection: any
  firebase_core: 2.10.0
  firebase_analytics: 10.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: 0.3.0
  golden_toolkit: 0.15.0

  flutter_lints: 2.0.1

  build_runner: 2.3.3
  auto_route_generator: 6.2.0

  flutter_launcher_icons: 0.13.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/vectors/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/tajawal/Tajawal-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/tajawal/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/tajawal/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/tajawal/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/tajawal/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/tajawal/Tajawal-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/tajawal/Tajawal-Black.ttf
          weight: 900
