name: alyamamah
description: An app for alyamamah university students.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  flutter_riverpod: 2.1.3
  auto_route: 5.0.4
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: 0.3.0
  golden_toolkit: 0.14.0

  flutter_lints: 2.0.1

  build_runner: 2.3.3
  auto_route_generator: 5.0.3

flutter:
  uses-material-design: true
  generate: true
