name: alyamamah
description: An app for alyamamah university students.
publish_to: "none"
version: 0.0.1+2

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_riverpod: 2.3.0
  auto_route: 5.0.4
  intl: any
  dio: 5.0.1
  dio_cookie_manager: 2.1.1
  cookie_jar: 3.0.1
  logging: 1.1.1
  shared_preferences: 2.0.18
  font_awesome_flutter: 10.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: 0.3.0
  golden_toolkit: 0.15.0

  flutter_lints: 2.0.1

  build_runner: 2.3.3
  auto_route_generator: 5.0.3

  flutter_launcher_icons: 0.12.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
  
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/tajawal/Tajawal-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/tajawal/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/tajawal/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/tajawal/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/tajawal/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/tajawal/Tajawal-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/tajawal/Tajawal-Black.ttf
          weight: 900
