version: "3.1"

services:
  db:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root
      POSTGRES_DB: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432

networks:
  default:
    name: alyamamah_network
