arb-dir: lib/l10n
template-arb-file: en.arb
output-localization-file: app_localizations.dart
untranslated-messages-file: untranslated-messages.json
output-class: S
synthetic-package: true
# output-dir: lib/gen/l10n