name: alyamamah
description: An app for alyamamah university students.
publish_to: "none"
version: 0.0.9+40

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_riverpod: 2.4.9
  auto_route: 7.8.4
  intl: any
  dio: 5.4.0
  dio_cookie_manager: 2.1.3 # check this
  cookie_jar: 3.0.1 # check this
  logging: 1.2.0
  shared_preferences: 2.2.2
  home_widget: 0.4.0
  url_launcher: 6.2.1
  hijri: 3.0.0
  flutter_svg: 2.0.9
  collection: any
  firebase_core: 2.24.1
  firebase_analytics: 10.7.3
  firebase_messaging: 14.7.7
  sentry_flutter: 7.13.2
  sentry_logging: 7.13.2
  sentry_dio: 7.13.2
  flutter_animate: 4.3.0
  unleash_proxy_client_flutter: 1.4.0
  permission_handler: 11.1.0
  flutter_inappwebview: 5.8.0
  crypto: 3.0.3
  package_info_plus: 5.0.1
  grpc: 3.2.4
  protobuf: 3.1.0
  formz: 0.6.1
  html: 0.15.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: 1.0.1
  golden_toolkit: 0.15.0

  flutter_lints: 3.0.1

  build_runner: 2.4.7
  auto_route_generator: 7.3.2

  flutter_launcher_icons: 0.13.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/

  fonts:
    - family: IBM Plex Sans Arabic
      fonts:
        - asset: assets/fonts/IBM_Plex_Sans_Arabic/IBMPlexSansArabic-Thin.ttf
          weight: 100
        - asset: assets/fonts/IBM_Plex_Sans_Arabic/IBMPlexSansArabic-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/IBM_Plex_Sans_Arabic/IBMPlexSansArabic-Light.ttf
          weight: 300
        - asset: assets/fonts/IBM_Plex_Sans_Arabic/IBMPlexSansArabic-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBM_Plex_Sans_Arabic/IBMPlexSansArabic-Medium.ttf
          weight: 500
        - asset: assets/fonts/IBM_Plex_Sans_Arabic/IBMPlexSansArabic-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/IBM_Plex_Sans_Arabic/IBMPlexSansArabic-Bold.ttf
          weight: 700
