// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: feedback_category.sql

package sqlc

import (
	"context"
)

const listFeedbackCategory = `-- name: ListFeedbackCategory :many
SELECT id, name_ar, name_en FROM feedback_category
`

func (q *Queries) ListFeedbackCategory(ctx context.Context) ([]FeedbackCategory, error) {
	rows, err := q.db.QueryContext(ctx, listFeedbackCategory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FeedbackCategory
	for rows.Next() {
		var i FeedbackCategory
		if err := rows.Scan(&i.ID, &i.NameAr, &i.NameEn); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
