// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package sqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Feedback struct {
	ID                     uuid.UUID
	UserID                 uuid.UUID
	CategoryID             uuid.UUID
	Title                  string
	Body                   string
	CreatedAt              time.Time
	UpdatedAt              time.Time
	StudentID              sql.NullString
	StudentName            sql.NullString
	StudentEmail           sql.NullString
	StudentPhone           sql.NullString
	StudentMajor           sql.NullString
	StudentJoinSemester    sql.NullString
	StudentCurrentSemester sql.NullString
	StudentGender          sql.NullString
	StudentRemainingHours  sql.NullInt32
	StudentTakenHours      sql.NullInt32
	StudentTotalHours      sql.NullInt32
}

type FeedbackCategory struct {
	ID     uuid.UUID
	NameAr string
	NameEn string
}
