// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type Feedback struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	CategoryID uuid.UUID
	Title      string
	Body       string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type FeedbackCategory struct {
	ID     uuid.UUID
	NameAr string
	NameEn string
}
