// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package sqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID              uuid.UUID
	Username        string
	FcmToken        sql.NullString
	CreatedAt       time.Time
	UpdatedAt       time.Time
	IsEmailVerified bool
}

type VerifyEmail struct {
	ID        uuid.UUID
	Username  string
	Token     string
	ExpiresAt time.Time
	UsedAt    sql.NullTime
	CreatedAt time.Time
	UpdatedAt time.Time
}
