// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.3
// source: proto/feedback.proto

package feedbackpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetFeedbackCategoriesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetFeedbackCategoriesRequest) Reset() {
	*x = GetFeedbackCategoriesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_feedback_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFeedbackCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedbackCategoriesRequest) ProtoMessage() {}

func (x *GetFeedbackCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_feedback_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedbackCategoriesRequest.ProtoReflect.Descriptor instead.
func (*GetFeedbackCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_proto_feedback_proto_rawDescGZIP(), []int{0}
}

type FeedbackCategory struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NameAr string `protobuf:"bytes,2,opt,name=name_ar,json=nameAr,proto3" json:"name_ar,omitempty"`
	NameEn string `protobuf:"bytes,3,opt,name=name_en,json=nameEn,proto3" json:"name_en,omitempty"`
}

func (x *FeedbackCategory) Reset() {
	*x = FeedbackCategory{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_feedback_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FeedbackCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedbackCategory) ProtoMessage() {}

func (x *FeedbackCategory) ProtoReflect() protoreflect.Message {
	mi := &file_proto_feedback_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedbackCategory.ProtoReflect.Descriptor instead.
func (*FeedbackCategory) Descriptor() ([]byte, []int) {
	return file_proto_feedback_proto_rawDescGZIP(), []int{1}
}

func (x *FeedbackCategory) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FeedbackCategory) GetNameAr() string {
	if x != nil {
		return x.NameAr
	}
	return ""
}

func (x *FeedbackCategory) GetNameEn() string {
	if x != nil {
		return x.NameEn
	}
	return ""
}

type GetFeedbackCategoriesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Categories []*FeedbackCategory `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
}

func (x *GetFeedbackCategoriesResponse) Reset() {
	*x = GetFeedbackCategoriesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_feedback_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFeedbackCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedbackCategoriesResponse) ProtoMessage() {}

func (x *GetFeedbackCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_feedback_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedbackCategoriesResponse.ProtoReflect.Descriptor instead.
func (*GetFeedbackCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_proto_feedback_proto_rawDescGZIP(), []int{2}
}

func (x *GetFeedbackCategoriesResponse) GetCategories() []*FeedbackCategory {
	if x != nil {
		return x.Categories
	}
	return nil
}

type CreateFeedbackRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title                  string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Body                   string `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	CategoryId             string `protobuf:"bytes,3,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	StudentId              string `protobuf:"bytes,4,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	StudentName            string `protobuf:"bytes,5,opt,name=student_name,json=studentName,proto3" json:"student_name,omitempty"`
	StudentEmail           string `protobuf:"bytes,6,opt,name=student_email,json=studentEmail,proto3" json:"student_email,omitempty"`
	StudentPhone           string `protobuf:"bytes,7,opt,name=student_phone,json=studentPhone,proto3" json:"student_phone,omitempty"`
	StudentMajor           string `protobuf:"bytes,8,opt,name=student_major,json=studentMajor,proto3" json:"student_major,omitempty"`
	StudentJoinSemester    string `protobuf:"bytes,9,opt,name=student_join_semester,json=studentJoinSemester,proto3" json:"student_join_semester,omitempty"`
	StudentCurrentSemester string `protobuf:"bytes,10,opt,name=student_current_semester,json=studentCurrentSemester,proto3" json:"student_current_semester,omitempty"`
	StudentGender          string `protobuf:"bytes,11,opt,name=student_gender,json=studentGender,proto3" json:"student_gender,omitempty"`
	StudentRemainingHours  int32  `protobuf:"varint,12,opt,name=student_remaining_hours,json=studentRemainingHours,proto3" json:"student_remaining_hours,omitempty"`
	StudentTakenHours      int32  `protobuf:"varint,13,opt,name=student_taken_hours,json=studentTakenHours,proto3" json:"student_taken_hours,omitempty"`
	StudentTotalHours      int32  `protobuf:"varint,14,opt,name=student_total_hours,json=studentTotalHours,proto3" json:"student_total_hours,omitempty"`
}

func (x *CreateFeedbackRequest) Reset() {
	*x = CreateFeedbackRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_feedback_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFeedbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFeedbackRequest) ProtoMessage() {}

func (x *CreateFeedbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_feedback_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFeedbackRequest.ProtoReflect.Descriptor instead.
func (*CreateFeedbackRequest) Descriptor() ([]byte, []int) {
	return file_proto_feedback_proto_rawDescGZIP(), []int{3}
}

func (x *CreateFeedbackRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateFeedbackRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *CreateFeedbackRequest) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *CreateFeedbackRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *CreateFeedbackRequest) GetStudentName() string {
	if x != nil {
		return x.StudentName
	}
	return ""
}

func (x *CreateFeedbackRequest) GetStudentEmail() string {
	if x != nil {
		return x.StudentEmail
	}
	return ""
}

func (x *CreateFeedbackRequest) GetStudentPhone() string {
	if x != nil {
		return x.StudentPhone
	}
	return ""
}

func (x *CreateFeedbackRequest) GetStudentMajor() string {
	if x != nil {
		return x.StudentMajor
	}
	return ""
}

func (x *CreateFeedbackRequest) GetStudentJoinSemester() string {
	if x != nil {
		return x.StudentJoinSemester
	}
	return ""
}

func (x *CreateFeedbackRequest) GetStudentCurrentSemester() string {
	if x != nil {
		return x.StudentCurrentSemester
	}
	return ""
}

func (x *CreateFeedbackRequest) GetStudentGender() string {
	if x != nil {
		return x.StudentGender
	}
	return ""
}

func (x *CreateFeedbackRequest) GetStudentRemainingHours() int32 {
	if x != nil {
		return x.StudentRemainingHours
	}
	return 0
}

func (x *CreateFeedbackRequest) GetStudentTakenHours() int32 {
	if x != nil {
		return x.StudentTakenHours
	}
	return 0
}

func (x *CreateFeedbackRequest) GetStudentTotalHours() int32 {
	if x != nil {
		return x.StudentTotalHours
	}
	return 0
}

type CreateFeedbackResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateFeedbackResponse) Reset() {
	*x = CreateFeedbackResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_feedback_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFeedbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFeedbackResponse) ProtoMessage() {}

func (x *CreateFeedbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_feedback_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFeedbackResponse.ProtoReflect.Descriptor instead.
func (*CreateFeedbackResponse) Descriptor() ([]byte, []int) {
	return file_proto_feedback_proto_rawDescGZIP(), []int{4}
}

type FeedbackItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title    string            `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Body     string            `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Category *FeedbackCategory `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
}

func (x *FeedbackItem) Reset() {
	*x = FeedbackItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_feedback_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FeedbackItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedbackItem) ProtoMessage() {}

func (x *FeedbackItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_feedback_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedbackItem.ProtoReflect.Descriptor instead.
func (*FeedbackItem) Descriptor() ([]byte, []int) {
	return file_proto_feedback_proto_rawDescGZIP(), []int{5}
}

func (x *FeedbackItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FeedbackItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *FeedbackItem) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *FeedbackItem) GetCategory() *FeedbackCategory {
	if x != nil {
		return x.Category
	}
	return nil
}

type GetFeedbackRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id *string `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
}

func (x *GetFeedbackRequest) Reset() {
	*x = GetFeedbackRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_feedback_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFeedbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedbackRequest) ProtoMessage() {}

func (x *GetFeedbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_feedback_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedbackRequest.ProtoReflect.Descriptor instead.
func (*GetFeedbackRequest) Descriptor() ([]byte, []int) {
	return file_proto_feedback_proto_rawDescGZIP(), []int{6}
}

func (x *GetFeedbackRequest) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

type GetFeedbackResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FeedbackItems []*FeedbackItem `protobuf:"bytes,1,rep,name=feedback_items,json=feedbackItems,proto3" json:"feedback_items,omitempty"`
}

func (x *GetFeedbackResponse) Reset() {
	*x = GetFeedbackResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_feedback_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFeedbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedbackResponse) ProtoMessage() {}

func (x *GetFeedbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_feedback_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedbackResponse.ProtoReflect.Descriptor instead.
func (*GetFeedbackResponse) Descriptor() ([]byte, []int) {
	return file_proto_feedback_proto_rawDescGZIP(), []int{7}
}

func (x *GetFeedbackResponse) GetFeedbackItems() []*FeedbackItem {
	if x != nil {
		return x.FeedbackItems
	}
	return nil
}

var File_proto_feedback_proto protoreflect.FileDescriptor

var file_proto_feedback_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1e, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x46, 0x65, 0x65,
	0x64, 0x62, 0x61, 0x63, 0x6b, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x54, 0x0a, 0x10, 0x46, 0x65, 0x65, 0x64, 0x62, 0x61,
	0x63, 0x6b, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x6e, 0x61,
	0x6d, 0x65, 0x5f, 0x61, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x61, 0x6d,
	0x65, 0x41, 0x72, 0x12, 0x17, 0x0a, 0x07, 0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x65, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x61, 0x6d, 0x65, 0x45, 0x6e, 0x22, 0x52, 0x0a, 0x1d,
	0x47, 0x65, 0x74, 0x46, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x43, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a,
	0x0a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x46, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x43, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x52, 0x0a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73,
	0x22, 0xc0, 0x04, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x65, 0x65, 0x64, 0x62,
	0x61, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x62, 0x6f, 0x64, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x75, 0x64, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x74, 0x75, 0x64,
	0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x74, 0x75, 0x64, 0x65,
	0x6e, 0x74, 0x5f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x23, 0x0a, 0x0d,
	0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x5f, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x50, 0x68, 0x6f, 0x6e,
	0x65, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x5f, 0x6d, 0x61, 0x6a,
	0x6f, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e,
	0x74, 0x4d, 0x61, 0x6a, 0x6f, 0x72, 0x12, 0x32, 0x0a, 0x15, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e,
	0x74, 0x5f, 0x6a, 0x6f, 0x69, 0x6e, 0x5f, 0x73, 0x65, 0x6d, 0x65, 0x73, 0x74, 0x65, 0x72, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x4a, 0x6f,
	0x69, 0x6e, 0x53, 0x65, 0x6d, 0x65, 0x73, 0x74, 0x65, 0x72, 0x12, 0x38, 0x0a, 0x18, 0x73, 0x74,
	0x75, 0x64, 0x65, 0x6e, 0x74, 0x5f, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x65,
	0x6d, 0x65, 0x73, 0x74, 0x65, 0x72, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x16, 0x73, 0x74,
	0x75, 0x64, 0x65, 0x6e, 0x74, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x6d, 0x65,
	0x73, 0x74, 0x65, 0x72, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x5f,
	0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x74,
	0x75, 0x64, 0x65, 0x6e, 0x74, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x36, 0x0a, 0x17, 0x73,
	0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x5f, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67,
	0x5f, 0x68, 0x6f, 0x75, 0x72, 0x73, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x05, 0x52, 0x15, 0x73, 0x74,
	0x75, 0x64, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x48, 0x6f,
	0x75, 0x72, 0x73, 0x12, 0x2e, 0x0a, 0x13, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x5f, 0x74,
	0x61, 0x6b, 0x65, 0x6e, 0x5f, 0x68, 0x6f, 0x75, 0x72, 0x73, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x11, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x54, 0x61, 0x6b, 0x65, 0x6e, 0x48, 0x6f,
	0x75, 0x72, 0x73, 0x12, 0x2e, 0x0a, 0x13, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x5f, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x68, 0x6f, 0x75, 0x72, 0x73, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x11, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x48, 0x6f,
	0x75, 0x72, 0x73, 0x22, 0x18, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x65, 0x65,
	0x64, 0x62, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x77, 0x0a,
	0x0c, 0x46, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x2d, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x46, 0x65, 0x65, 0x64,
	0x62, 0x61, 0x63, 0x6b, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x08, 0x63, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x22, 0x30, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x46, 0x65, 0x65,
	0x64, 0x62, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x13, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x02, 0x69, 0x64, 0x88, 0x01,
	0x01, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x69, 0x64, 0x22, 0x4b, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x46,
	0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x34, 0x0a, 0x0e, 0x66, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x5f, 0x69, 0x74, 0x65, 0x6d,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x46, 0x65, 0x65, 0x64, 0x62, 0x61,
	0x63, 0x6b, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x0d, 0x66, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b,
	0x49, 0x74, 0x65, 0x6d, 0x73, 0x32, 0xdf, 0x01, 0x0a, 0x08, 0x46, 0x65, 0x65, 0x64, 0x62, 0x61,
	0x63, 0x6b, 0x12, 0x56, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x46, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63,
	0x6b, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x12, 0x1d, 0x2e, 0x47, 0x65,
	0x74, 0x46, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x47, 0x65, 0x74,
	0x46, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69,
	0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a, 0x0e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x46, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x12, 0x16, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x65, 0x65,
	0x64, 0x62, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a,
	0x0b, 0x47, 0x65, 0x74, 0x46, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x12, 0x13, 0x2e, 0x47,
	0x65, 0x74, 0x46, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x14, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x48, 0x5a, 0x46, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x59, 0x61, 0x7a, 0x65, 0x65, 0x64, 0x41, 0x6c, 0x4b, 0x68,
	0x61, 0x6c, 0x61, 0x66, 0x2f, 0x61, 0x6c, 0x79, 0x61, 0x6d, 0x61, 0x6d, 0x61, 0x68, 0x2f, 0x71,
	0x75, 0x61, 0x73, 0x61, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x66, 0x65,
	0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x3b, 0x66, 0x65, 0x65, 0x64, 0x62, 0x61, 0x63, 0x6b, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_feedback_proto_rawDescOnce sync.Once
	file_proto_feedback_proto_rawDescData = file_proto_feedback_proto_rawDesc
)

func file_proto_feedback_proto_rawDescGZIP() []byte {
	file_proto_feedback_proto_rawDescOnce.Do(func() {
		file_proto_feedback_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_feedback_proto_rawDescData)
	})
	return file_proto_feedback_proto_rawDescData
}

var file_proto_feedback_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_feedback_proto_goTypes = []interface{}{
	(*GetFeedbackCategoriesRequest)(nil),  // 0: GetFeedbackCategoriesRequest
	(*FeedbackCategory)(nil),              // 1: FeedbackCategory
	(*GetFeedbackCategoriesResponse)(nil), // 2: GetFeedbackCategoriesResponse
	(*CreateFeedbackRequest)(nil),         // 3: CreateFeedbackRequest
	(*CreateFeedbackResponse)(nil),        // 4: CreateFeedbackResponse
	(*FeedbackItem)(nil),                  // 5: FeedbackItem
	(*GetFeedbackRequest)(nil),            // 6: GetFeedbackRequest
	(*GetFeedbackResponse)(nil),           // 7: GetFeedbackResponse
}
var file_proto_feedback_proto_depIdxs = []int32{
	1, // 0: GetFeedbackCategoriesResponse.categories:type_name -> FeedbackCategory
	1, // 1: FeedbackItem.category:type_name -> FeedbackCategory
	5, // 2: GetFeedbackResponse.feedback_items:type_name -> FeedbackItem
	0, // 3: Feedback.GetFeedbackCategories:input_type -> GetFeedbackCategoriesRequest
	3, // 4: Feedback.CreateFeedback:input_type -> CreateFeedbackRequest
	6, // 5: Feedback.GetFeedback:input_type -> GetFeedbackRequest
	2, // 6: Feedback.GetFeedbackCategories:output_type -> GetFeedbackCategoriesResponse
	4, // 7: Feedback.CreateFeedback:output_type -> CreateFeedbackResponse
	7, // 8: Feedback.GetFeedback:output_type -> GetFeedbackResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_feedback_proto_init() }
func file_proto_feedback_proto_init() {
	if File_proto_feedback_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_feedback_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFeedbackCategoriesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_feedback_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FeedbackCategory); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_feedback_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFeedbackCategoriesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_feedback_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateFeedbackRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_feedback_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateFeedbackResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_feedback_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FeedbackItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_feedback_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFeedbackRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_feedback_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFeedbackResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_feedback_proto_msgTypes[6].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_feedback_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_feedback_proto_goTypes,
		DependencyIndexes: file_proto_feedback_proto_depIdxs,
		MessageInfos:      file_proto_feedback_proto_msgTypes,
	}.Build()
	File_proto_feedback_proto = out.File
	file_proto_feedback_proto_rawDesc = nil
	file_proto_feedback_proto_goTypes = nil
	file_proto_feedback_proto_depIdxs = nil
}
