name: Test
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2.8.0
        with:
          flutter-version: 3.7.6
          channel: 'stable'
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
          cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:'

      - name: Run `flutter pub get`
        run: flutter pub get

      - name: Generate coverage helper
        run: ./scripts/01-coverage-helper.sh

      - name: Run `flutter test --coverage`
        run: "flutter test --coverage"

      - name: Upload `test` folder
        if: success() || failure()
        uses: actions/upload-artifact@v3.1.2
        with:
          name: test
          path: test/

      - name: Test Reporter
        if: success() || failure()
        uses: dorny/test-reporter@v1.6.0
        with:
          name: Flutter Tests
          path: reports/test-results.json
          reporter: flutter-json

      - name: Install lcov
        run: brew install lcov

      - name: Remove generated coverage
        run: ./scripts/02-remove-generated-coverage.sh

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
